name: Run pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: autoyapf
      id: autoyapf
      uses: mritunjaysharma394/autoyapf@v2
      with:
        args: --style pep8 --recursive --in-place .
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Github Action Robot
        author_email: robot@example.com
        message: 'Auto format python files'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
